# Generated by Django 4.0.1 on 2022-01-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='provincia',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
