# Generated by Django 4.0.1 on 2022-01-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='apellido',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='celular',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='provincia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
