# Generated by Django 4.0.1 on 2022-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='celular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='educacion',
            field=models.CharField(choices=[('prim_inc', 'Primario incompleto'), ('prim_comp', 'Primario completo'), ('sec_inc', 'Secundario incompleto'), ('sec_comp', 'Secundario completo'), ('terc_inc', 'Terciario incompleto'), ('terc_comp', 'Terciario completo'), ('uni_inc', 'Universitario incompleto'), ('uni_comp', 'Universitario completo')], max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Dovorciado'), ('viudo', 'Viudo'), ('concubinato', 'Concubinato'), ('unioncivil', 'Unión civil')], max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='fec_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otre', 'Otre')], max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='identidad',
            field=models.CharField(blank=True, choices=[('mujercis', 'Mujer'), ('hombrecis', 'Hombre'), ('mujertrans', 'Mujer trans'), ('hombretrans', 'Hombre trans'), ('nobinarie', 'No binarie'), ('nodeclara', 'Prefiero no decir')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='provincia',
            field=models.CharField(choices=[('buenosaires', 'Buenos Aires'), ('caba', 'Ciudad Autónoma de Buenos Aires'), ('catamarca', 'Catamarca'), ('chaco', 'Chaco'), ('chubut', 'Chubut'), ('cordoba', 'Córdoba'), ('honeydew', 'Honeydews'), ('corrientes', 'Corrientes'), ('entrerios', 'Entre Ríos'), ('formosa', 'Formosa'), ('jujuy', 'Jujuy'), ('lapampa', 'La Pampa'), ('larioja', 'La Rioja'), ('mendoza', 'Mendoza'), ('misiones', 'Misiones'), ('neuquen', 'Neuquén'), ('rionegro', 'Río Negro'), ('salta', 'Salta'), ('sanjuan', 'San Juan'), ('sanluis', 'San Luis'), ('santacruz', 'Santa Cruz'), ('santafe', 'Santa Fe'), ('santiagoestero', 'Santiago del Estero'), ('tierafuego', 'Tierra del Fuego'), ('tucuman', 'Tucumán')], max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
