# Generated by Django 4.0.1 on 2022-01-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_solicitud_domicilio_emp'),
        ('accounts', '0003_alter_emprendedor_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.domicilio'),
        ),
    ]
