# Generated by Django 4.0.1 on 2022-01-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emprendedor_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Dovorciado'), ('Viudo', 'Viudo'), ('Concubinato', 'Concubinato'), ('Unión Civil', 'Unión civil')], max_length=200, null=True),
        ),
    ]
