# Generated by Django 4.0.1 on 2022-01-29 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_solicitud_domicilio_emp'),
        ('accounts', '0005_alter_emprendedor_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='domicilio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prestamos.domicilio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='educacion',
            field=models.CharField(choices=[('Primario incompleto', 'Primario incompleto'), ('Primario Completo', 'Primario completo'), ('Primario completo', 'Secundario incompleto'), ('Secundario completo', 'Secundario completo'), ('Terciario incompleto', 'Terciario incompleto'), ('Terciario completo', 'Terciario completo'), ('Universitario incompleto', 'Universitario incompleto'), ('Universitario completo', 'Universitario completo')], max_length=200, null=True),
        ),
    ]
