# Generated by Django 4.0.1 on 2022-02-07 04:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('piso', models.CharField(blank=True, max_length=20)),
                ('depto', models.CharField(blank=True, max_length=20)),
                ('monoblock', models.CharField(blank=True, max_length=20)),
                ('kilometro', models.CharField(blank=True, max_length=20)),
                ('barrio', models.CharField(blank=True, max_length=200)),
                ('manzana', models.CharField(blank=True, max_length=20)),
                ('seccion', models.CharField(blank=True, max_length=20)),
                ('casa', models.CharField(blank=True, max_length=20)),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('CABA', 'CABA'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200)),
                ('municipio', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=200)),
                ('cod_postal', models.CharField(blank=True, max_length=20)),
                ('condicion', models.CharField(choices=[('Propio', 'Propio'), ('Alquilado', 'Alquilado'), ('Prestado', 'Prestado'), ('Leasing', 'Leasing'), ('Otro', 'Otro')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SMVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('descripcion_emp', models.TextField()),
                ('rubro', models.CharField(choices=[('Producción', 'Producción'), ('Comercialización', 'Comercialización'), ('Servicios', 'Servicios')], max_length=200)),
                ('inicio_actividad', models.DateField()),
                ('datos_contacto', models.IntegerField(blank=True)),
                ('personal_familiar', models.IntegerField()),
                ('personal_nofamiliar', models.IntegerField()),
                ('ingreso_emp_mes', models.IntegerField()),
                ('gastos_emp', models.IntegerField()),
                ('resultado_emp', models.IntegerField(null=True)),
                ('ingresos_familiares_mes', models.IntegerField(blank=True, null=True)),
                ('gastos_familiares_mes', models.IntegerField(blank=True, null=True)),
                ('resultado_familiar', models.IntegerField(null=True)),
                ('resultado_total', models.IntegerField(null=True)),
                ('notas', models.TextField(blank=True)),
                ('importe_solicitado', models.PositiveIntegerField()),
                ('cant_cuotas', models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('9', '9'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=200)),
                ('tasa_anual', models.PositiveIntegerField()),
                ('destino1_texto', models.CharField(max_length=50, null=True)),
                ('destino1_monto', models.IntegerField(null=True)),
                ('destino2_texto', models.CharField(max_length=50, null=True)),
                ('destino2_monto', models.IntegerField(null=True)),
                ('destino3_texto', models.CharField(max_length=50, null=True)),
                ('destino3_monto', models.IntegerField(null=True)),
                ('cuota_final', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('domicilio_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilioemp', to='prestamos.domicilio')),
                ('domicilio_viv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilioviv', to='prestamos.domicilio')),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor', to=settings.AUTH_USER_MODEL)),
                ('smvm', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.smvm')),
                ('tasa_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.tasainteres')),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('importe_solicitado', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tasa_anual', models.PositiveIntegerField()),
                ('cant_cuotas', models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('9', '9'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cuota_final', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('smvm', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.smvm')),
                ('tasa_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.tasainteres')),
            ],
        ),
    ]
