# Generated by Django 4.0.1 on 2022-01-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='smvm',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.smvm'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='importe_solicitado',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tasa_interes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.tasainteres'),
        ),
    ]
