# Generated by Django 4.0.1 on 2022-01-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smvm',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tasainteres',
            name='tasa',
            field=models.PositiveIntegerField(),
        ),
    ]
