# Generated by Django 4.0.1 on 2022-02-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
