# Generated by Django 4.0.1 on 2022-01-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_simulacion_monto_alter_simulacion_smvm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='smvm',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.smvm'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
