# Generated by Django 4.0.1 on 2022-01-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_smvm_monto_alter_tasainteres_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='domicilio_emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='domicilioemp', to='prestamos.domicilio'),
            preserve_default=False,
        ),
    ]
