# Generated by Django 4.0.1 on 2022-01-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_solicitud_smvm_alter_solicitud_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='resultado_emp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resultado_familiar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resultado_total',
            field=models.IntegerField(null=True),
        ),
    ]
