# Generated by Django 4.0.1 on 2022-01-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_solicitud_resultado_emp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='destino1_monto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='destino1_texto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='destino2_monto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='destino2_texto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='destino3_monto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='destino3_texto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
