# Generated by Django 4.0.1 on 2022-01-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_alter_solicitud_destino1_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='domicilio_viv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilioviv', to='prestamos.domicilio'),
        ),
    ]
