# Generated by Django 4.0.1 on 2022-01-30 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_alter_solicitud_gastos_familiares_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='domicilio_emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='domicilioemp', to='prestamos.domicilio'),
            preserve_default=False,
        ),
    ]
