# Generated by Django 4.0.1 on 2022-02-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_alter_solicitud_domicilio_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='cant_cuotas',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('9', '9'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cant_cuotas',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('9', '9'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=200),
        ),
    ]
