# Generated by Django 4.0.1 on 2022-01-22 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0007_solicitud_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='emprendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
