# Generated by Django 4.0.1 on 2022-02-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_alter_simulacion_cant_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='tasa_anual',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
