# Generated by Django 4.0.1 on 2022-01-23 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0010_alter_domicilio_condicion_alter_domicilio_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='domicilio_viv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilioviv', to=settings.AUTH_USER_MODEL),
        ),
    ]
