# Generated by Django 4.0.1 on 2022-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_alter_solicitud_domicilio_viv'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cuota_final',
            field=models.SmallIntegerField(default=15),
            preserve_default=False,
        ),
    ]
