# Generated by Django 4.0.1 on 2022-01-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_solicitud_cuota_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cuota_final',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
