# Generated by Django 4.0.1 on 2022-01-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0014_alter_solicitud_cuota_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulacion',
            old_name='monto',
            new_name='importe_solicitado',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='tasa_interes',
            new_name='tasa_anual',
        ),
    ]
