# Generated by Django 4.0.1 on 2022-01-24 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0015_rename_monto_simulacion_importe_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
