# Generated by Django 4.0.1 on 2022-01-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0021_alter_solicitud_domicilio_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='actividad',
            field=models.CharField(choices=[('Producción', 'Producción'), ('Comercialización', 'Comercialización'), ('Servicios', 'Servicios')], default=2, max_length=200),
            preserve_default=False,
        ),
    ]
