# Generated by Django 4.0.1 on 2022-01-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0022_solicitud_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='actividad',
            new_name='rubro',
        ),
    ]
